env:
  es6: true
  node: true
  browser: true
parserOptions:
  sourceType: module
  ecmaVersion: 6
  ecmaFeatures:
    experimentalObjectRestSpread: true
extends:
  - eslint:recommended
rules:
  semi:
    - 2
    - never
  no-undef:
    - 0
  no-unused-vars: 0
  no-useless-escape: 0
  no-console: 0
  quotes:
    - 2
    - single
